### ISSUE TITLE
Is this package Jetson specific?

### ISSUE THREAD

**Issue by r1b4z01d** [jdgalviss/TFMiniPlusROS#1]
I was wondering if this package is Jetson-specific. I am trying to compile it on another compute board running Ubuntu 20 and I can not compile it without errors. I have not looked much into it but it errors out on the i2c driver so this is why I raised the question. 

Errors     << tf_mini_plus_ros:make /root/rosws/logs/tf_mini_plus_ros/build.make.004.log
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp: In member function ‘uint16 I2C::read_register16(uint16)’:
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp:38:13: error: ‘i2c_smbus_read_word_data’ was not declared in this scope
   38 |  int read = i2c_smbus_read_word_data(kI2CFileDescriptor, reg);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp: In member function ‘uint16 I2C::read_register16(uint16)’:
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp:38:13: error: ‘i2c_smbus_read_word_data’ was not declared in this scope
   38 |  int read = i2c_smbus_read_word_data(kI2CFileDescriptor, reg);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp: In member function ‘uint16 I2C::read_register_block(uint16, uint8*)’:
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp:47:13: error: ‘i2c_smbus_read_block_data’ was not declared in this scope; did you mean ‘i2c_smbus_ioctl_data’?
   47 |  int read = i2c_smbus_read_block_data(kI2CFileDescriptor, reg, values);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |             i2c_smbus_ioctl_data
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp: In member function ‘uint16 I2C::read_register_block(uint16, uint8*)’:
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp:47:13: error: ‘i2c_smbus_read_block_data’ was not declared in this scope; did you mean ‘i2c_smbus_ioctl_data’?
   47 |  int read = i2c_smbus_read_block_data(kI2CFileDescriptor, reg, values);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |             i2c_smbus_ioctl_data
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp: In member function ‘uint16 I2C::write_register16(uint8, uint16)’:
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp:59:13: error: ‘i2c_smbus_write_word_data’ was not declared in this scope; did you mean ‘i2c_smbus_ioctl_data’?
   59 |  int resp = i2c_smbus_write_word_data(kI2CFileDescriptor, device_register, write);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |             i2c_smbus_ioctl_data
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp: In member function ‘uint16 I2C::write_register_block(uint8, uint8, uint8*)’:
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp:67:13: error: ‘i2c_smbus_write_block_data’ was not declared in this scope; did you mean ‘i2c_smbus_ioctl_data’?
   67 |  int resp = i2c_smbus_write_block_data(kI2CFileDescriptor, device_register, length, values);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |             i2c_smbus_ioctl_data
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp: In member function ‘uint16 I2C::write_register16(uint8, uint16)’:
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp:59:13: error: ‘i2c_smbus_write_word_data’ was not declared in this scope; did you mean ‘i2c_smbus_ioctl_data’?
   59 |  int resp = i2c_smbus_write_word_data(kI2CFileDescriptor, device_register, write);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |             i2c_smbus_ioctl_data
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp: In member function ‘int I2C::read(uint8)’:
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp:76:13: error: ‘i2c_smbus_read_byte_data’ was not declared in this scope; did you mean ‘i2c_smbus_ioctl_data’?
   76 |  int read = i2c_smbus_read_byte_data(kI2CFileDescriptor, reg);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~
      |             i2c_smbus_ioctl_data
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp: In member function ‘uint16 I2C::write_register_block(uint8, uint8, uint8*)’:
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp:67:13: error: ‘i2c_smbus_write_block_data’ was not declared in this scope; did you mean ‘i2c_smbus_ioctl_data’?
   67 |  int resp = i2c_smbus_write_block_data(kI2CFileDescriptor, device_register, length, values);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |             i2c_smbus_ioctl_data
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp: In member function ‘int I2C::write_register8(uint8, uint8)’:
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp:84:13: error: ‘i2c_smbus_write_byte_data’ was not declared in this scope; did you mean ‘i2c_smbus_ioctl_data’?
   84 |  int resp = i2c_smbus_write_byte_data(kI2CFileDescriptor, device_register, value);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |             i2c_smbus_ioctl_data
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp: In member function ‘int I2C::read(uint8)’:
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp:76:13: error: ‘i2c_smbus_read_byte_data’ was not declared in this scope; did you mean ‘i2c_smbus_ioctl_data’?
   76 |  int read = i2c_smbus_read_byte_data(kI2CFileDescriptor, reg);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~
      |             i2c_smbus_ioctl_data
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp: In member function ‘int I2C::write(uint8)’:
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp:93:14: error: ‘i2c_smbus_write_byte’ was not declared in this scope
   93 |  int write = i2c_smbus_write_byte(kI2CFileDescriptor, writeValue);
      |              ^~~~~~~~~~~~~~~~~~~~
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp: In member function ‘int I2C::write_register8(uint8, uint8)’:
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp:84:13: error: ‘i2c_smbus_write_byte_data’ was not declared in this scope; did you mean ‘i2c_smbus_ioctl_data’?
   84 |  int resp = i2c_smbus_write_byte_data(kI2CFileDescriptor, device_register, value);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |             i2c_smbus_ioctl_data
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp: In member function ‘int I2C::write(uint8)’:
/root/rosws/src/TFMiniPlusROS/tf_mini_plus_ros/src/drivers/i2c.cpp:93:14: error: ‘i2c_smbus_write_byte’ was not declared in this scope
   93 |  int write = i2c_smbus_write_byte(kI2CFileDescriptor, writeValue);
      |              ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/range_sensor_node.dir/build.make:63: CMakeFiles/range_sensor_node.dir/src/drivers/i2c.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:171: CMakeFiles/range_sensor_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/change_address_node.dir/build.make:63: CMakeFiles/change_address_node.dir/src/drivers/i2c.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:725: CMakeFiles/change_address_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
cd /root/rosws/build/tf_mini_plus_ros; catkin build --get-env tf_mini_plus_ros | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

**Comment by jdgalviss** [comment]
Hi, the problem is the operating system. It only works on ubuntu 16.04 and lower. From ubuntu 18.04 some of the functions I was using for the i2c driver were deprecated, so the driver needs to be updated for it to work on ubuntu 18 and 20. I haven't worked on this in a while so I never updated it. If you can fix it, feel free to create a PR  :)
